### ISSUE TITLE
Linux failure

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/avro-feedstock#1]
Seeing a build issue with this recipe. Here is the [log](https://circleci.com/gh/conda-forge/avro-feedstock/1) and a traceback snippet is shown below.

```
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.5/site-packages/conda_build/main_build.py", line 144, in main
    args_func(args, p)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/main_build.py", line 389, in args_func
    args.func(args, p)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/main_build.py", line 332, in execute
    dirty=args.dirty, activate=args.activate)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/build.py", line 478, in build
    has_vcs_available = os.path.isfile(external.find_executable(vcs_executable))
  File "/opt/conda/lib/python3.5/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: can't specify None for path argument
```

**Comment by mariusvniekerk** [comment]
Not sure what this means....

Is it having difficulty downloading the source archive?

**Comment by mariusvniekerk** [comment]
this should apparently only happen if its downloading from a version control system (which is isn't...)

**Comment by mariusvniekerk** [comment]
Fixed it it seems
